### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by jmarhee** [packet-labs/packetnet-fw-agent#13] opened 2019-11-12 08:11 UTC
Add to `packet-labs/helm-charts`, potentially as a `DaemonSet`-- let the CCM `Secret` provide auth, and the only require `SEEK_TAG` to find the cluster tag.

**Comment by displague** [comment] 2022-01-18 21:41
Duplicate of https://github.com/packet-labs/helm-charts/issues/3 - Closing as this project will be archived.

**Closed by displague** 2022-01-18 21:41 UTC
Labels: enhancement
